### ISSUE TITLE
pkg build error

### ISSUE THREAD

**Issue by tonyxjoseph** [Sushipool/source#2]
HI
when trying to run ./build.sh
getting error
no available node version satisfies node9
nodejs9.11.2 installed
pkg@4.3.4 ubuntu 16.04

**Comment by joewandy** [comment]
This seems to be a bug with pkg 4.3.4. Downgrade to 4.3.1 instead, and it should work fine. 

https://github.com/zeit/pkg/issues/331

**Comment by tonyxjoseph** [comment]
im unable to find any doc to downgrade
or how to remove 4.3.4 and install 4.3.1

**Comment by joewandy** [comment]
It's an npm thing :) take a look at https://stackoverflow.com/questions/15890958/how-do-i-install-a-previous-version-of-an-npm-package

**Comment by tonyxjoseph** [comment]
i setup another machine and install pkg@4.3.1
now there is no error
but getting another one pkg: command not found when running ./build.sh

**Comment by joewandy** [comment]
Make sure pkg is installed correctly and is in your path. If you just type 'pkg' in bash, is it found?

**Comment by tonyxjoseph** [comment]
pkg is now working.
but getting following error.
Creating package at ./binaries/sushipool-win-x86-1.3.1-win                                                                                                                                                                                               
> pkg@4.3.1                                                                                                                                                                                                                                              
> Warning Failed to make bytecode node9-x86 for file C:\snapshot\miner\index.js error (spawn /root/.pkg-cache/v2.5/fetched-v9.2.1-linux-x86 ENOENT)                                                                                                      
> Warning Failed to make bytecode node9-x86 for file C:\snapshot\miner\node_modules\@nimiq\core\dist\node.js error (spawn /root/.pkg-cache/v2.5/fetched-v9.2.1-linux-x86 ENOENT)                                                                         
> Warning Failed to make bytecode node9-x86 for file C:\snapshot\miner\src\Config.js error (spawn /root/.pkg-cache/v2.5/fetched-v9.2.1-linux-x86 ENOENT)                                                                                                 
> Warning Failed to make bytecode node9-x86 for file C:\snapshot\miner\src\SushiPoolMiner.js error (spawn /root/.pkg-cache/v2.5/fetched-v9.2.1-linux-x86 ENOENT)                                                                                         
> Warning Failed to make bytecode node9-x86 for file C:\snapshot\miner\src\ServerFinder.js error (spawn /root/.pkg-cache/v2.5/fetched-v9.2.1-linux-x86 ENOENT)                                                                                           
> Warning Failed to make bytecode node9-x86 for file C:\snapshot\miner\node_modules\readline-sync\lib\readline-sync.js error (spawn /root/.pkg-cache/v2.5/fetched-v9.2.1-linux-x86 ENOENT)                                                               
> Warning Failed to make bytecode node9-x86 for file C:\snapshot\miner\node_modules\minimist\index.js error (spawn /root/.pkg-cache/v2.5/fetched-v9.2.1-linux-x86 ENOENT)                                                                                
> Warning Failed to make bytecode node9-x86 for file C:\snapshot\miner\node_modules\@nimiq\jungle-db\dist\lmdb.js error (spawn /root/.pkg-cache/v2.5/fetched-v9.2.1-linux-x86 ENOENT)                                                                    
> Warning Failed to make bytecode node9-x86 for file C:\snapshot\miner\node_modules\atob\node-atob.js error (spawn /root/.pkg-cache/v2.5/fetched-v9.2.1-linux-x86 ENOENT)                                                                                
> Warning Failed to make bytecode node9-x86 for file C:\snapshot\miner\node_modules\bindings\bindings.js error (spawn /root/.pkg-cache/v2.5/fetched-v9.2.1-linux-x86 ENOENT)                                                                             
> Warning Failed to make bytecode node9-x86 for file C:\snapshot\miner\node_modules\btoa\index.js error (spawn /root/.pkg-cache/v2.5/fetched-v9.2.1-linux-x86 ENOENT)

**Comment by joewandy** [comment]
Seems like an issue with pkg? https://github.com/zeit/pkg/issues/310

**Comment by tonyxjoseph** [comment]
build complete without any error
copied everything to a windows 
now another error

c:\sushipool.exe

pkg/prelude/bootstrap.js:1172
      throw error;
      ^

Error: \\?\C:\~~\no
de-lmdb.node is not a valid Win32 application.
\\?\C:\~~node-lmdb
.node
    at Object.Module._extensions..node (module.js:668:18)
    at Module.load (module.js:558:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:583:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:11:18)
    at bindings (C:\snapshot\miner\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (C:\snapshot\miner\node_modules\node-lmdb\index.js:3:3
7)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)

**Comment by joewandy** [comment]
You can't use Linux to build the Windows binaries, so you have to use Windows to do it. Alternatively you can also download our release.
